### ISSUE TITLE
 cannot import name 'UNIT_PERCENTAGE'

### ISSUE THREAD

**Issue by tehbra1n** [eifinger/hass-foldingathomecontrol#11]
## Version of the custom_component
VERSION = "2.0.1"
## Configuration

foldingathomecontrol:
  - address: "192.168.1.130"
    port: 36330
    #password: "password"

Add your logs here.

`Sep 19 09:25:26 ultra hass[734]: 2020-09-19 09:25:26 ERROR (MainThread) [homeassistant.components.homeassistant] Component error: foldingathomecontrol - cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/srv/homeassistant/lib/python3.8/site-packages/homeassistant/const.py)`

## Describe the bug
The HACS integration throws this error on start up.  Just doing some digging I can up with: UNIT_PERCENTAGE was changed to PERCENTAGE in 0.115. The integration needs to update their code. Please open a github issue on the integration’s repo

```

**Comment by SirGoodenough** [comment]
I see it also....
```
Log Details (ERROR)
Logger: homeassistant.setup
Source: setup.py:138
First occurred: 1:51:49 AM (1 occurrences)
Last logged: 1:51:49 AM

Setup failed for foldingathomecontrol: Unable to import component: cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
Home Assistant has started!

```
