### ISSUE TITLE
All entities show as "Unknown"

### ISSUE THREAD

**Issue by jb123567** [eifinger/hass-foldingathomecontrol#118]
## Configuration

Version 2.0.14

Setup using default port and no password.

Add your logs here.

Debug mode enabled by no errors in the logs.

## Describe issue

Intergration sets up correctly, however all entities show as unknown. Have left it setup for 24 hours with no change.

## Debug log

No apparent logging

**Comment by eifinger** [comment]
Thank you for opening an issue. I can reproduce it and will provide a fix as soon as I found the bug.

**Comment by jb123567** [comment]
> Thank you for opening an issue. I can reproduce it and will provide a fix as soon as I found the bug.

I thought I was going mad, if you need it testing let me know!

**Comment by eifinger** [comment]
I found the bug but have problems getting the tests to run.
In the meantime you can downgrade to v2.0.13 which does not have the bug.

**Comment by eifinger** [comment]
Fixed by https://github.com/eifinger/hass-foldingathomecontrol/commit/afa7d3ba01b4ac0fbf7aaac00db7cd06a892372d

**Comment by jb123567** [comment]
> @jb123567 in my instance v2.0.15 fixes the issue. Can you confirm?

Works for me, thank you!!
