### ISSUE TITLE
Adjust Power Level

### ISSUE THREAD

**Issue by albarlow** [eifinger/hass-foldingathomecontrol#127]
**Is your feature request related to a problem? Please describe.**
I don't want to uses full power when the house is occupied during the day as the processor fan noise is noticeable.

**Describe the solution you'd like**
I would like to be able to make a service call to change the power level.

**Describe alternatives you've considered**
I don't have any other ideas.

**Additional context**

**Comment by eifinger** [comment]
Hi @albarlow thank you for suggesting the functionality. Took me a while to figure out the correct commands but the new releave [v.2.1.0](https://github.com/eifinger/hass-foldingathomecontrol/releases/tag/v2.1.0) does offer a service to control the power now.
![image](https://user-images.githubusercontent.com/1481961/153085801-55205dcc-225e-4567-8b03-ce3fec203c4a.png)
