### ISSUE TITLE
Data inconsistent with 2 WU at same slot

### ISSUE THREAD

**Issue by JanosAudron** [eifinger/hass-foldingathomecontrol#4]
## Version of the custom_component
v0.0.1

## Describe the bug
If one slot has at same time 2 work units (one running and one trying to download), data are inconsistent because attributes report RUNNING state, but percentdone: 0% and nextattempt: 4m 50s

![image](https://user-images.githubusercontent.com/1606318/78471262-48b24680-7730-11ea-973d-fafcbd05e208.png)
![image](https://user-images.githubusercontent.com/1606318/78471266-4d76fa80-7730-11ea-9940-f1e9ef941ce8.png)

**Comment by eifinger** [comment]
I didn't know there could me more units than slots. Interesting.

Currently there is a single sensor for every slot with many attributes.

The plan for the next release was to create a single device for every slot with many sensors.

How would you like the different work units to be handled? A sensor, a device?

The device sensors only showing the values for the current work unit and an additional sensor "total work units in queue"?

**Comment by eifinger** [comment]
Another idea would be, to ignore all other workunits for a slot of one is already running

**Comment by JanosAudron** [comment]
Maybe having a device would be more powerful infrastructure for future development. Instead, ignoring all other WU if one is already running would be faster to implement. You might fix quickly using second choice, and then implement a more complex structure based on device for next release.

**Comment by eifinger** [comment]
@JanosAudron I just released [v1.0.0](https://github.com/eifinger/hass-foldingathomecontrol/releases/tag/v1.0.0) where the work queue with the "RUNNING" label takes precedence.

**Comment by eifinger** [comment]
**BREAKING CHANGE**
Please remove all entries for this integration, update and then readd them.
**BREAKING CHANGE**

**Comment by eifinger** [comment]
There hasn't been any updates on this issue. If your issue still persists feel free to reopen. Thank you!
