### ISSUE TITLE
Less frequent event updates

### ISSUE THREAD

**Issue by scstanton** [eifinger/hass-foldingathomecontrol#6]
Issue: foldingathomecontrol submits too much data to the events database.  After installing, it tripled the size of my database in just a few days.

Suggestion: Less frequent or configurable polling/state updates, or document that this integration can cause substantial database growth.

**Comment by eifinger** [comment]
@scstanton I just released [v1.0.0](https://github.com/eifinger/hass-foldingathomecontrol/releases/tag/v1.0.0) with this option added.

Does this solve your issue?

**Comment by eifinger** [comment]
**BREAKING CHANGE**
Please remove all entries for this integration, update and then readd them.
**BREAKING CHANGE**

**Comment by eifinger** [comment]
There hasn't been any updates on this issue. If your issue still persists feel free to reopen. Thank you!
