### ISSUE TITLE
Remove % From Percentage Done State 

### ISSUE THREAD

**Issue by Shaun-Harrison** [eifinger/hass-foldingathomecontrol#8]
Version : 1.0.0

The state value for percentage done contains a % which means when trying to use for example the custom:bar-card it displays like it is always full like this 
![image](https://user-images.githubusercontent.com/46562010/81551134-3d7ab800-9379-11ea-9d91-ebef7e0859b0.png)

Where as if the state was without the % it would display as expected

**Comment by eifinger** [comment]
Thank you for noticing and opening an issue!
v1.1.0 fixes that.

**Comment by Shaun-Harrison** [comment]
Working now as expected in v1.1.0, thank you very much for the quick fix and for all the work your doing in this repo!
