### ISSUE TITLE
Sensors briefly go to Unknown at update

### ISSUE THREAD

**Issue by baronKanon** [eifinger/hass-foldingathomecontrol#9]
## Version of the custom_component
1.0.0
## Configuration
Default configuration from integrations page.
Update interval 30

## Describe the bug
I notice that at each update, the sensor briefly goes to "unknown" state before retrieving new state. This means that numerical values always go to 0 before updating, so the trends look quite strange there. 

## Debug log
No logs available

**Comment by eifinger** [comment]
Could you post a screenshot of the trend?
Also, are there any error messages in your log?

**Comment by eifinger** [comment]
What is your configured read timeout?

**Comment by baronKanon** [comment]
![image](https://user-images.githubusercontent.com/33922582/81804978-5a022600-951a-11ea-95f5-484112c43c2b.png)
The trend has been somewhat off, due to some restarts, etc, but you see the main trend there. What is strange, is that when following the trend on the mouse, it is counting up to the next update.

The configured timeout has been tried for both 15 and 30 (is this seconds? No description in the UI). I have tried both update interval 30 and 60 (seconds or minutes?)

Log shows something like this:
![image](https://user-images.githubusercontent.com/33922582/81805832-d9442980-951b-11ea-8f3d-ee6923d0dff8.png)

**Comment by eifinger** [comment]
The trend you showed here is completely normal. It goes up from 0%-100% when working on a WorkUnit. Then it gets assigned a new Workunit and starts at 0%.

**Comment by baronKanon** [comment]
You are right about that one :)

But it still blinks unknown when updating the values. That should not be, right?

**Comment by baronKanon** [comment]
While we have been discussing, the number of logged problems has grown:
![image](https://user-images.githubusercontent.com/33922582/81807174-e9f59f00-951d-11ea-97b1-6f984a477d4c.png)

**Comment by eifinger** [comment]
The dip on the far right is somewhat interesting. It is not that unknown is interpreted as 0, the folding@home client did report back "0".

As for the settings:
Both are in seconds.
It does not make sense to have a bigger update rate than read timeout.

The Integration waits <read_timeout> seconds for the next message from the server. After that it disposes the connection and tries to reconnect again.

The update rate is something which is not controlled by the Integration. The Folding@Home client is told that it should send updates every <update_rate> second.

If you told the F@H client to only provide updates every 30s but you say that the connection is to be handled as dead after 15s (read_timeout). You will actually reconnect every 15s and thus have a short unknown followed by the first update after the reconnect.

**Comment by baronKanon** [comment]
Thanks for the explanation. Will I need to restart Home Assistant to update the settings?

**Comment by eifinger** [comment]
No changing the options on an Integration managed via UI never require a restart.

**Comment by baronKanon** [comment]
That did it. Set the update rate to 60s and timeout to 70, and it last update no issue. I think it maybe should be default with longer timeout than poll interval to make sure any time discrepancies in polling is not presented with the "issue" I was experiencing. ((?)

**Comment by eifinger** [comment]
Default UpdateRate should be 5 and ReadTimeout 15.
Was this different for you?

**Comment by baronKanon** [comment]
I left the timeout and set to 30 and later 60. Works now with 60/70. 

Close this issue, it is apparently user error

**Comment by eifinger** [comment]
I will add this to a known issues section in the docs. Thanks for reaching out!
