### ISSUE TITLE
The Username or Password is wrong

### ISSUE THREAD

**Issue by Weldawadyathink** [eifinger/hass-foldingathomecontrol#95]
## Configuration

```yaml

Cannot get it configured. 

```

## Describe the bug
When trying to connect to a FAH server, I get the error: "The Username or Password is wrong". I have confirmed that the IP address, port, and password I am using is correct. The access list in FAH is 0.0.0.0/0, so it should be accessible from anywhere. I have confirmed this by accessing it through the advanced FAH client on my laptop. HomeAssistant is on the exact same subnet as my FAH server, and my laptop, although FAH is NOT running on the HomeAssistant host. 

## Debug log

I can't find out how to get a log for setting up a component. I enabled logging as directed, but I can't find any reference in the logs to the new component. If you can provide some direction, I would be happy to post any logs I can.

**Comment by eifinger** [comment]
Hi, we can enable debug logging for the underlying library handling the connection and authentication:

```yaml
logger:
  logs:
    FoldingAtHomeControl: debug
```

**Comment by eifinger** [comment]
I received no updates on this and there is a new version out. Please reopen the issue if it still persists. Thank you!
